### ISSUE TITLE
Latest Build potion effects not separating per world. SWI

### ISSUE THREAD

**Issue by Grimwiire** [TriptychGames/SeparateWorldItems#1]
This server is running CraftBukkit version git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

Latest build SWI.

Players are able to go to creative and keep potion effects using multiverse via /warp creative and /spawn.

CONFIG+GROUPS: http://pastebin.com/QWMnhpPy

**Comment by TriptychGames** [comment]
I'll start looking into it.

**Comment by TriptychGames** [comment]
Okay this is a just a temp fix but if you enable separate-gamemode-inventories: to true it should start to separate every inventory when you change gamemode. like i said it's just a temp fix i think i know whats happening.

**Comment by Grimwiire** [comment]
Thank you. I didn't know how to fix. For now I just added a full potion list to the prevent usage list in essentials and gave essentials.protect.exemptusage to all worlds but creative. Other than this the plugin is working amazingly.
