### ISSUE TITLE
command features maybe

### ISSUE THREAD

**Issue by soulji** [TriptychGames/SeparateWorldItems#3]
This is what I would like to see from this plugin:

/swi creategroup skyfactory
/swi addworld skyfactory skyfactoryworld
/swi delworld skyfactory skyfactoryworld
/swi delgroup skyfactory

Would this be possible, with the changes being saved into the groups.yml?

**Comment by TriptychGames** [comment]
This is a planed feature to be added just not at the top of the list saying there's a few bug that should be fix first.
