### ISSUE TITLE
SWI Issue

### ISSUE THREAD

**Issue by GrailBH** [TriptychGames/SeparateWorldItems#5]
I'm having a problem configuring this properly. As far as I can tell this would be simple... all I want to do is separate the inventory of my creative seed called "buildworld" and my survival seed called "mainworld", and keep the inventory for mainworld and it's nether and the_end linked... but it's just not working.

This is my groups.yml

groups:
  creativeworld:
    worlds:
    - buildworld
    default-gamemode: Creative
  default:
    worlds:
    - mainworld
    - mainworld_nether
    - mainworld_the_end
    default-gamemode: SURVIVAL

this is my config.yml

reset-config: false
manage-gamemodes: false
separate-gamemode-inventories: false
player:
  ender-chest: true
  inventory: false
  stats: true
player-stats:
  can-fly: true
  display-name: false
  exhaustion: true
  exp: true
  food: true
  flying: true
  gamemode: false
  health: true
  level: true
  potion-effects: false
  saturation: true

Can you please tell me where I'm going wrong here?

**Comment by TriptychGames** [comment]
Okay i left you a template to fix this remember that it's yml files so watch your how much you use Tab.

groups:
  main:
    worlds:
    - mainworld
    - mainworld_nether
    - mainworld_the_end
    default-gamemode: SURVIVAL
  Creative:
    worlds:
    - buildworld
    default-gamemode: CREATIVE
